
version: 2

models:
    - name: mart_trip
      description: "Trip Data"
      columns:
          - name: trip_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: mart_order
      description: "A starter dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: mart_customer
      description: "A starter dbt model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: mart_aeroplane_details
      description: "A starter dbt model"
      columns:
          - name: aeroplane_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
